services:
  server:
    build: .
    image: "holyknight101/backend_patent-analyzer_v1"
    container_name: "backend"
    ports:
      - 8000:8000
    depends_on:
      - selenium-firefox
    env_file:
      - .env
    networks:
      - app-net
    # Optional health check to ensure `server` starts only when dependencies are ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]  # Update this endpoint as per your server's health check
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

  selenium-firefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium-firefox
    ports:
      - "4444:4444"
    shm_size: "2gb"
    networks:
      - app-net
    # Optional: Health check to ensure Selenium container is fully ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]  # Selenium WebDriver status
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

networks:
  app-net:
    driver: bridge
