[project]
name = "beta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "cohere>=5.15.0",
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "langchain>=0.3.25",
    "openai>=1.76.2",
    "pydantic>=2.11.4",
    "qdrant-client>=1.14.2",
    "selenium>=4.31.0",
    "together>=1.5.6",
    "waitress>=3.0.2",
]
